name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  ECS_CLUSTER: mycluster
  ECS_SERVICE: myservice
  ECS_CONTAINER: mycontainer
  IMAGE_TAG: latest
  DOCKER_HUB_USERNAME: your-docker-hub-username
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/express:${{ env.IMAGE_TAG }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Update ECS service
        uses: einaregilsson/ecs-deploy@v2
        with:
          region: ${{ env.AWS_REGION }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          image: ${{ env.DOCKER_HUB_USERNAME }}/myimage:${{ env.IMAGE_TAG }}
          container: ${{ env.ECS_CONTAINER }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
